CREATE TABLE BENEFICIO (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  VALOR DECIMAL(15,2) NOT NULL,
  ATIVO BOOLEAN DEFAULT TRUE,
  VERSION BIGINT DEFAULT 0
);

CREATE TABLE CLIENTE (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR(150) NOT NULL,
  EMAIL VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE CONTA_BENEFICIO (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CLIENTE_ID BIGINT NOT NULL,
  BENEFICIO_ID BIGINT NOT NULL,
  SALDO DECIMAL(15,2) NOT NULL,
  VERSION BIGINT DEFAULT 0,
  CONSTRAINT FK_CONTA_BENEFICIO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
  CONSTRAINT FK_CONTA_BENEFICIO_BENEFICIO FOREIGN KEY (BENEFICIO_ID) REFERENCES BENEFICIO(ID),
  CONSTRAINT UK_CONTA_BENEFICIO_CLIENTE_BENEFICIO UNIQUE (CLIENTE_ID, BENEFICIO_ID)
);

CREATE TABLE TRANSACAO_BENEFICIO (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CONTA_ORIGEM_ID BIGINT NOT NULL,
  CONTA_DESTINO_ID BIGINT,
  VALOR DECIMAL(15,2) NOT NULL,
  TIPO VARCHAR(20) NOT NULL,
  DATA_HORA TIMESTAMP NOT NULL,
  CONSTRAINT FK_TRANSACAO_CONTA_ORIGEM FOREIGN KEY (CONTA_ORIGEM_ID) REFERENCES CONTA_BENEFICIO(ID),
  CONSTRAINT FK_TRANSACAO_CONTA_DESTINO FOREIGN KEY (CONTA_DESTINO_ID) REFERENCES CONTA_BENEFICIO(ID)
);
