INSERT INTO BENEFICIO (NOME, DESCRICAO, VALOR, ATIVO) VALUES
('Beneficio A', 'Descrição A', 1000.00, TRUE),
('Beneficio B', 'Descrição B', 500.00, TRUE);

INSERT INTO CLIENTE (NOME, EMAIL) VALUES
('Cliente 1', 'cliente1@example.com'),
('Cliente 2', 'cliente2@example.com');

INSERT INTO CONTA_BENEFICIO (CLIENTE_ID, BENEFICIO_ID, SALDO) VALUES
(1, 1, 1000.00), -- Cliente 1, Beneficio A
(1, 2, 500.00),  -- Cliente 1, Beneficio B
(2, 1, 200.00);  -- Cliente 2, Beneficio A

INSERT INTO TRANSACAO_BENEFICIO (CONTA_ORIGEM_ID, CONTA_DESTINO_ID, VALOR, TIPO, DATA_HORA) VALUES
(1, 2, 100.00, 'TRANSFERENCIA', CURRENT_TIMESTAMP),
(1, NULL, 50.00, 'DEBITO', CURRENT_TIMESTAMP),
(2, NULL, 75.00, 'CREDITO', CURRENT_TIMESTAMP);
